-- name: UpsertSwitches :batchexec
INSERT INTO switches (node_id, node_guid, linear_fdb_cap, random_fdb_cap, mcast_fdb_cap,
                      linear_fdb_top, def_port, def_mcast_pri_port, def_mcast_not_pri_port,
                      life_time_value, port_state_change, optimized_slvl_mapping,
                      lids_per_port, part_enf_cap, inb_enf_cap, outb_enf_cap,
                      filter_raw_inb_cap, filter_raw_outb_cap, enp0, mcast_fdb_top)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8, $9, $10, $11, $12,
        $13, $14, $15, $16, $17, $18,
        $19, $20)
ON CONFLICT (node_id) DO UPDATE SET linear_fdb_cap         = COALESCE(EXCLUDED.linear_fdb_cap, switches.linear_fdb_cap),
                                    random_fdb_cap         = COALESCE(EXCLUDED.random_fdb_cap, switches.random_fdb_cap),
                                    mcast_fdb_cap          = COALESCE(EXCLUDED.mcast_fdb_cap, switches.mcast_fdb_cap),
                                    linear_fdb_top         = COALESCE(EXCLUDED.linear_fdb_top, switches.linear_fdb_top),
                                    def_port               = COALESCE(EXCLUDED.def_port, switches.def_port),
                                    def_mcast_pri_port     = COALESCE(EXCLUDED.def_mcast_pri_port, switches.def_mcast_pri_port),
                                    def_mcast_not_pri_port = COALESCE(EXCLUDED.def_mcast_not_pri_port,
                                                                      switches.def_mcast_not_pri_port),
                                    life_time_value        = COALESCE(EXCLUDED.life_time_value, switches.life_time_value),
                                    port_state_change      = COALESCE(EXCLUDED.port_state_change, switches.port_state_change),
                                    optimized_slvl_mapping = COALESCE(EXCLUDED.optimized_slvl_mapping,
                                                                      switches.optimized_slvl_mapping),
                                    lids_per_port          = COALESCE(EXCLUDED.lids_per_port, switches.lids_per_port),
                                    part_enf_cap           = COALESCE(EXCLUDED.part_enf_cap, switches.part_enf_cap),
                                    inb_enf_cap            = COALESCE(EXCLUDED.inb_enf_cap, switches.inb_enf_cap),
                                    outb_enf_cap           = COALESCE(EXCLUDED.outb_enf_cap, switches.outb_enf_cap),
                                    filter_raw_inb_cap     = COALESCE(EXCLUDED.filter_raw_inb_cap, switches.filter_raw_inb_cap),
                                    filter_raw_outb_cap    = COALESCE(EXCLUDED.filter_raw_outb_cap, switches.filter_raw_outb_cap),
                                    enp0                   = COALESCE(EXCLUDED.enp0, switches.enp0),
                                    mcast_fdb_top          = COALESCE(EXCLUDED.mcast_fdb_top, switches.mcast_fdb_top);