[SERVICE]
    Flush        1
    Log_Level    info

[INPUT]
    Name         forward
    Listen       0.0.0.0
    Port         24224

[OUTPUT]
    Name         http
    Match        *
    Host         victorialogs
    Port         9428
    Compress     gzip
    URI          /insert/jsonline?_stream_fields=container_name&_msg_field=log
    Format       json_lines
    Header       Content-Type application/json