DROP TABLE IF EXISTS switches;
DROP TABLE IF EXISTS nodes_info;
DROP TABLE IF EXISTS ports;
DROP TABLE IF EXISTS nodes;
DROP TABLE IF EXISTS logs;

DROP TYPE IF EXISTS node_kind;
DROP TYPE IF EXISTS log_status;